language: python

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7-dev
          env: TOXENV=py37

install:
      - "pip install tox"
      - "pip install -r requirements.txt"
      - "pip install -r requirements_dev.txt"

script:
      - "tox -e $TOXENV"